import Head from 'next/head'
import styles from '../styles/Home.module.css'
import getData from '../lib/getData'
import { useState } from 'react'
import List from '../components/List'

const Home = () => {
  const [list, setList] = useState([]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const search = e.target.search.value;
    const result = await getData(search)
    setList(result)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello</h1>
        <form onSubmit={(e) => handleSubmit(e)}>
          <input 
            name='search'
            id='search'
            type='text'
            placeholder='Type something'
            required
            />
          <button>Search</button>
        </form>
        <List elements={list} />
      </main>

    </div>
  )
}

export default Home;